name: CI-iOS

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master
        
      - name: Prepare ionic build
        uses: coturiv/setup-ionic@v1

      - name: Run ionic build
        run: |
          npm install --silent
          ionic cap update --no-interactive --no-open --confirm
          ionic cap build ios --no-interactive --no-open --confirm
  
      - name: Run iOS build
        uses: sparkfabrik/ios-build-action@v1.1.0
        with:
          project-path: ./ios/App/App.xcodeproj
          workspace-path: ./ios/App/App.xcworkspace
          pods-path: ./ios/App/Podfile
          p12-base64: ${{ secrets.IOS_DISTRIBUTION_P12 }}
          certificate-password: ${{ secrets.IOS_DISTRIBUTION_PASSWORD }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION }}
          code-signing-identity: ${{ secrets.IOS_CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.IOS_TEAM_ID }}

  deploy-ios:
    needs: [build-ios]
    runs-on: macOS-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master
      
      # TODO: get build artifacts
      - name: Download build artifact
        run: echo "TODO"
      #  uses: actions/download-artifact@master
      #  with:
      #    name: ipa-artifact
      #    path: simport-learning-app.ipa
      
      # TODO: add firebase secret to run this step
      - name: Deploy to Firebase
        run: echo "TODO"
      #  uses: w9jds/firebase-action@master
      #  with:
      #    args: deploy --only hosting
      #  env:
      #    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
