name: CI

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Prepare ionic build
        uses: coturiv/setup-ionic@v1

      # TODO: add flag --prod (currently not building)
      - name: Run ionic build
        run: |
          ionic cap update 
          ionic cap build android --no-interactive --no-open --confirm
          
      - name: Run Android build
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: android
          output-path: simport-learning-app.apk
          
      - name: Publish
        run: |
          echo "TODO: publish"
        
  build-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Prepare ionic build
        uses: coturiv/setup-ionic@v1

      - name: Run ionic build
        run: |
          ionic cap update 
          ionic cap build ios --no-interactive --no-open --confirm
          
      - name: Run iOS build
        uses: sparkfabrik/ios-build-action@v1.1.0
        with:
          project-path: ios/App/App.xcodeproj
          workspace-path: ios/App/App.xcworkspace
          pods-path: ios/App/Podfile
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
        
      - name: Publish
        run: |
          echo "TODO: publish"
