name: CI

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8

      - name: Build Android
        run: |
          ionic cap build android --prod
          
      - name: Publish
        run: |
          echo "TODO: publish"
        
