name: CI

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master
        
      - name: Prepare ionic build
        uses: coturiv/setup-ionic@v1

      # TODO: add flag --prod (currently not building)
      - name: Run ionic build
        run: |
          npm install --silent
          ionic cap update --no-interactive --no-open --confirm
          ionic cap build android --no-interactive --no-open --confirm
          
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.0.3
        with:
          ndk-version: r21d

      - name: Setup Android keystore
        working-directory: ./android
        run: |
              echo $SIGNING_KEY | base64 -di > $PATH_TO_KEYSTORE
        env:
          SIGNING_KEY: ${{ secrets.ANDROID_KEYSTORE }}
          PATH_TO_KEYSTORE: ${{ secrets.ANDROID_PATH_TO_KEYSTORE }}

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  
      - name: Build with Gradle
        working-directory: ./android
        run: ./gradlew assembleRelease
        env:
          ANDROID_PATH_TO_KEYSTORE: ${{ secrets.ANDROID_PATH_TO_KEYSTORE }}
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        
      - name: Archive build artifact
        uses: actions/upload-artifact@master
        with:
          name: apk-artifact
          path: android/app/build/outputs/apk/release/app-release.apk
        
  deploy-android:
    needs: [build-android]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master
      
      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: apk-artifact
          path: ./
      
      # TODO: add firebase secret to run this step
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app-release.apk
    
  build-ios:
    runs-on: macOS-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master
        
      - name: Prepare ionic build
        uses: coturiv/setup-ionic@v1

      - name: Run ionic build
        run: |
          npm install --silent
          ionic cap update --no-interactive --no-open --confirm
          ionic cap build ios --no-interactive --no-open --confirm
      
    # TODO: add keys to run this step    
     # - name: Run iOS build
     #   uses: sparkfabrik/ios-build-action@v1.1.0
     #   with:
     #     project-path: ios/App/App.xcodeproj
     #     workspace-path: ios/App/App.xcworkspace
     #     pods-path: ios/App/Podfile
     #     p12-base64: ${{ secrets.P12_BASE64 }}
     #     mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
     #     code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
     #     team-id: ${{ secrets.TEAM_ID }}

  deploy-ios:
    needs: [build-ios]
    runs-on: macOS-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@master
      
      # TODO: get build artifacts
      - name: Download build artifact
        run: echo "TODO"
      #  uses: actions/download-artifact@master
      #  with:
      #    name: ipa-artifact
      #    path: simport-learning-app.ipa
      
      # TODO: add firebase secret to run this step
      - name: Deploy to Firebase
        run: echo "TODO"
      #  uses: w9jds/firebase-action@master
      #  with:
      #    args: deploy --only hosting
      #  env:
      #    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
